//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.24 at 07:22:57 AM CET 
//


package org.DNA.mixtures.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.DNA.mixtures.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Person_QNAME = new QName("", "person");
    private final static QName _Mixture_QNAME = new QName("", "mixture");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.DNA.mixtures.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MarkersType }
     * 
     */
    public MarkersType createMarkersType() {
        return new MarkersType();
    }

    /**
     * Create an instance of {@link MixtureType }
     * 
     */
    public MixtureType createMixtureType() {
        return new MixtureType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link MarkerType }
     * 
     */
    public MarkerType createMarkerType() {
        return new MarkerType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "person")
    public JAXBElement<PersonType> createPerson(PersonType value) {
        return new JAXBElement<PersonType>(_Person_QNAME, PersonType.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixtureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mixture")
    public JAXBElement<MixtureType> createMixture(MixtureType value) {
        return new JAXBElement<MixtureType>(_Mixture_QNAME, MixtureType.class, null, value);
    }
}
